### PR TITLE
add models, create serializers

### PR DESCRIPTION
**Pull request by iman-bolotbek-uulu**

### CODE REVIEW

**Review by iman-bolotbek-uulu — COMMENTED** [review]
ok

**Review by iman-bolotbek-uulu — COMMENTED** [review]
ok

**Review by iman-bolotbek-uulu — COMMENTED** [review]
ok

**Review by iman-bolotbek-uulu — COMMENTED** [review]
kjfkdjfsd

**Comment by Miwa-Abidin** [comment]
ok

**Pull request merged**
